In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
# roc curve and auc score
from sklearn.datasets import make_classification

In [2]:
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=2000, n_classes=2, weights=[1,1], random_state=1)

In [4]:
X.shape

(2000, 20)

In [5]:
y

array([0, 0, 0, ..., 1, 1, 0])

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [7]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [8]:
## Apply RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
ytrain_pred = rf_model.predict_proba(X_train)
print('RF train roc-auc: {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
ytest_pred = rf_model.predict_proba(X_test)
print('RF test roc-auc: {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

C:\Users\rohit\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RF train roc-auc: 0.99989795730942
RF test roc-auc: 0.9754166666666668


In [9]:
ytrain_pred

array([[1. , 0. ],
       [0.8, 0.2],
       [0. , 1. ],
       ...,
       [1. , 0. ],
       [1. , 0. ],
       [0.1, 0.9]])

In [10]:
from sklearn.linear_model import LogisticRegression
log_classifier=LogisticRegression()
log_classifier.fit(X_train, y_train)
ytrain_pred = log_classifier.predict_proba(X_train)
print('Logistic train roc-auc: {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
ytest_pred = log_classifier.predict_proba(X_test)
print('Logistic test roc-auc: {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

C:\Users\rohit\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Logistic train roc-auc: 0.9863589331232614
Logistic test roc-auc: 0.9885777777777777


In [11]:
from sklearn.ensemble import AdaBoostClassifier
ada_classifier=AdaBoostClassifier()
ada_classifier.fit(X_train, y_train)
ytrain_pred = ada_classifier.predict_proba(X_train)
print('Adaboost train roc-auc: {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
ytest_pred = ada_classifier.predict_proba(X_test)
print('Adaboost test roc-auc: {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

Adaboost train roc-auc: 0.9975081174960356
Adaboost test roc-auc: 0.9826111111111111


In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier=KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)
ytrain_pred = knn_classifier.predict_proba(X_train)
print('KNN train roc-auc: {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
ytest_pred = knn_classifier.predict_proba(X_test)
print('KNN test roc-auc: {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

KNN train roc-auc: 0.981670071491109
KNN test roc-auc: 0.9426111111111111


In [13]:
pred=[]
for model in [rf_model,log_classifier,ada_classifier,knn_classifier]:
    pred.append(pd.Series(model.predict_proba(X_test)[:,1]))
final_prediction=pd.concat(pred,axis=1).mean(axis=1)
print('Ensemble test roc-auc: {}'.format(roc_auc_score(y_test,final_prediction)))

Ensemble test roc-auc: 0.9855


In [14]:
pd.concat(pred,axis=1)

0         1         2    3
0    1.0  0.991869  0.559186  1.0
1    0.0  0.000008  0.463282  0.0
2    1.0  0.966761  0.538202  0.8
3    1.0  0.761461  0.509875  0.8
4    0.7  0.777991  0.490344  0.4
..   ...       ...       ...  ...
595  0.0  0.024096  0.461121  0.0
596  0.0  0.000003  0.441377  0.0
597  1.0  0.984375  0.532403  1.0
598  0.0  0.001142  0.441720  0.2
599  1.0  0.989553  0.559890  0.8

[600 rows x 4 columns]

In [15]:

final_prediction

0      0.887764
1      0.115823
2      0.826241
3      0.767834
4      0.592084
         ...   
595    0.121304
596    0.110345
597    0.879195
598    0.160715
599    0.837361
Length: 600, dtype: float64

In [16]:
#### Calculate the ROc Curve
fpr, tpr, thresholds = roc_curve(y_test, final_prediction)
thresholds

array([1.91424695, 0.91424695, 0.91156638, 0.91077267, 0.82026325,
       0.81907151, 0.7937895 , 0.79320261, 0.78075015, 0.780555  ,
       0.73918335, 0.73782624, 0.70256224, 0.70218131, 0.69493215,
       0.6937815 , 0.69048174, 0.68849235, 0.60375922, 0.60365575,
       0.60172764, 0.59762509, 0.58522617, 0.56722851, 0.54812654,
       0.54370183, 0.54296766, 0.53201661, 0.4690538 , 0.46212534,
       0.4469101 , 0.4348282 , 0.43373479, 0.39342106, 0.38342204,
       0.34857505, 0.33553337, 0.2938046 , 0.29315777, 0.22196586,
       0.22112022, 0.193297  , 0.19096876, 0.11794908, 0.11783509,
       0.10498954])

In [22]:
fpr

array([0.        , 0.        , 0.        , 0.00333333, 0.00333333,
       0.00666667, 0.00666667, 0.01      , 0.01      , 0.01333333,
       0.01333333, 0.01666667, 0.01666667, 0.02      , 0.02      ,
       0.02333333, 0.02333333, 0.02666667, 0.02666667, 0.03      ,
       0.03      , 0.03333333, 0.03333333, 0.04      , 0.04      ,
       0.04333333, 0.04333333, 0.05      , 0.05      , 0.05666667,
       0.05666667, 0.06333333, 0.06333333, 0.09      , 0.09      ,
       0.11666667, 0.11666667, 0.15333333, 0.15333333, 0.25      ,
       0.25      , 0.32666667, 0.32666667, 0.63666667, 0.63666667,
       1.        ])

In [23]:
from sklearn.metrics import accuracy_score
accuracy_ls = []
for thres in thresholds:
    y_pred = np.where(final_prediction>thres,1,0)
    accuracy_ls.append(accuracy_score(y_test, y_pred, normalize=True))
    
accuracy_ls = pd.concat([pd.Series(thresholds), pd.Series(accuracy_ls)],
                        axis=1)
accuracy_ls.columns = ['thresholds', 'accuracy']
accuracy_ls.sort_values(by='accuracy', ascending=False, inplace=True)
accuracy_ls.head()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

thresholds  accuracy
29    0.462125  0.960000
28    0.469054  0.960000
31    0.434828  0.958333
30    0.446910  0.958333
32    0.433735  0.956667

In [24]:
accuracy_ls

thresholds  accuracy
29    0.462125  0.960000
28    0.469054  0.960000
31    0.434828  0.958333
30    0.446910  0.958333
32    0.433735  0.956667
25    0.543702  0.956667
23    0.567229  0.955000
27    0.532017  0.955000
26    0.542968  0.955000
24    0.548127  0.955000
22    0.585226  0.955000
19    0.603656  0.951667
21    0.597625  0.951667
18    0.603759  0.950000
20    0.601728  0.950000
33    0.393421  0.946667
34    0.383422  0.945000
35    0.348575  0.935000
36    0.335533  0.933333
15    0.693781  0.928333
17    0.688492  0.928333
16    0.690482  0.926667
14    0.694932  0.926667
13    0.702181  0.923333
12    0.702562  0.921667
37    0.293805  0.918333
38    0.293158  0.916667
11    0.737826  0.890000
10    0.739183  0.888333
39    0.221966  0.871667
40    0.221120  0.870000
9     0.780555  0.835000
41    0.193297  0.835000
42    0.190969  0.833333
8     0.780750  0.833333
7     0.793203  0.815000
6     0.793790  0.813333
5     0.819072  0.780000
4     0.820263  0.778333
43    0.117949  0.681667
44    0.117835  0.680000
3     0.910773  0.513333
2     0.911566  0.511667
45    0.104990  0.501667
1     0.914247  0.500000
0     1.914247  0.500000

In [25]:
def plot_roc_curve(fpr, tpr):
    plt.plot(fpr, tpr, color='orange', label='ROC')
    plt.plot([0, 1], [0, 1], color='darkblue', linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic (ROC) Curve')
    plt.legend()
    plt.show()